In [1]:
#Exp no-5

In [2]:
#Aim:To create 1D,2D,and Multidimensional array

In [3]:
#Name:sanskruti ajay chandore
#Roll no.:09
#Subject:ET1
#Sec:C
#Date:19/08/2025

In [4]:
import numpy as np

In [5]:
#creating 1D array using numpy

In [6]:
a1=np.array([10,20,30,40,50])

In [7]:
a1

array([10, 20, 30, 40, 50])

In [8]:
a2=np.array([[10,20,30,40],[60,70,80,90]])

In [11]:
a2

array([[10, 20, 30, 40],
       [60, 70, 80, 90]])

In [ ]:
#creating 2D array using matrix

In [12]:
a3=np.matrix('11 22;33 44;55 66')
print(a3)

[[11 22]
 [33 44]
 [55 66]]
